#pragma once
#include <DirectX12/d3dx12.h>

namespace DX {
	enum class ShaderVisibilityFlag {
		All				= D3D12_SHADER_VISIBILITY_ALL,
		Vertex			= D3D12_SHADER_VISIBILITY_VERTEX,
		Hull			= D3D12_SHADER_VISIBILITY_HULL,
		Domain			= D3D12_SHADER_VISIBILITY_DOMAIN,
		Geometery		= D3D12_SHADER_VISIBILITY_GEOMETRY,
		Pixel			= D3D12_SHADER_VISIBILITY_PIXEL,
		Amplification	= D3D12_SHADER_VISIBILITY_AMPLIFICATION,
		Mesh			= D3D12_SHADER_VISIBILITY_MESH
	};
}
